name = "markdown"
description = "Markdown parser"
version = "26.0.0-dev"
tags = ["markdown", "gfm", "commonmark"]

authors = ["AdaCore"]
maintainers = ["Max Reznik <reznik@adacore.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"

project-files = ["gnat/markdown.gpr"]

[configuration]
generate_ada = false
generate_c = false

[build-switches]
"*".ada_version = "Ada2022"

[[depends-on]]
vss_text = "^26"
vss_extra = "^26"

[[pins]]
vss_text = { url='https://github.com/AdaCore/vss-text' }
vss_extra = { url='https://github.com/AdaCore/vss-extra' }
