on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [dev, prod]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get CommonMark Spec
        uses: actions/checkout@v3
        with:
          repository: commonmark/commonmark-spec
          path: commonmark-spec
          ref: 0.31.2
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v2
        with:
          toolchain: gnat_native^15 gprbuild^25
          version: "nightly"
      - name: Build and test
        shell: bash
        run: |
          #alr pin vss_text --use=https://github.com/AdaCore/vss-text
          #alr pin vss_extra --use=https://github.com/AdaCore/vss-extra
          alr exec -- make all check coverage BUILD_MODE=${{ matrix.build_mode }}
          alr exec -- make install PREFIX=/tmp BUILD_MODE=${{ matrix.build_mode }}
